version: '3'

volumes:
  db-data: {}

services:
  node:
    build: .
    ports:
     - 3000:3000
    volumes:
      - ./:/data
    links:
      - db
    depends_on:
      - db
    env_file: .env
  db:
    image: mariadb
    ports:
      - 3308:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env